package com.inventive.ugosmartbuddy.smartbuddy.models

class SaveRelayDataModel {
    var id: Int = 0
    var ACCOUNT_NO: String? = null
    var CONSUMER_NAME: String? = null
    var VISITED_DATE: String? = null
    var ADDRESS: String? = null
    var MOBILE_NO: String? = null
    var EMAIL_ID: String? = null
    var SUB_STATION_ID: Int = 0
    var SUB_STATION_CODE: String? = null
    var SUB_STATION_NAME: String? = null
    var OTHER_SUB_STATION_NAME: String? = null
    var COMPLAINT_ID: Int = 0
    var COMPLAINT_NO: String? = null
    var COMPLAINT_TYPE_NAME: String? = null
    var COMPLAINT_DESCRIPTION: String? = null
    var COMPLAINT_DATETIME: String? = null
    var COMPLAINT_STATUS: String? = null
    var PROCESS_SHORT_CODE: String? = null
    var SEARCH_FOR: String? = null
    var METER_NO: String? = null
    var METER_MAKE_ID: Int = 0
    var METER_MAKE_NAME: String? = null
    var PHASE_TYPE_ID: Int = 0
    var PHASE_TYPE_NAME: String? = null
    var METER_STATUS_ID: Int = 0
    var METER_STATUS_CODE: Int = 0
    var METER_STATUS_NAME: String? = null
    var OTP: String? = null
    var METER_IMAGE_1: String? = null
    var METER_IMAGE_2: String? = null
    var USER_ID: Int = 0
    var BATTERY_STATUS: String? = null
    var DEVICE_INFO: String? = null
    var DEVICE_ID: String? = null
    var APP_VERSION: String? = null
    var LATITUDE: String? = null
    var LONGITUDE: String? = null
    var IP_ADDRESS: String? = null
    var REMARK: String? = null
    var MRI_SUCCESS_FLAG: Boolean = false
    var DLMS_FLAG: Boolean = false
    var IS_UPLOADED: Boolean = false
    var IS_VISITED: Boolean = false
    var ERROR_CODE_ID:Int=0
    var ERROR_CODE_NAME:String?=null
    var ACTION:String?=null
    var ACTION_DATETIME:String?=null
    var ACTION_STATUS:String?=null
}